### PR TITLE
Fix checkUpdatedPackages for repos without any tags

### LINKED ISSUE #14: `git rev-list --tags --max-count=1` fails
It wants me to put `master` after rev-list in order to function.

### PR DESCRIPTION
**Pull request by thejameskyle**
Fixes #14

### CODE REVIEW

File: lib/commands/updated.js [hunk 1]
```diff
@@ -26,8 +26,14 @@ exports.checkUpdatedPackages = function (config) {
 
   var tick = progressBar(packageNames.length);
 
-  var lastTagCommit = execSync("git rev-list --tags --max-count=1");
-  var lastTag       = execSync("git describe " + lastTagCommit);
+  var hasTags = !!execSync("git tags");
```
Comment (hzoo) [inline lib/commands/updated.js]: Is this supposed to be `git tag`, since `git tags` isn't a command I don't think

Comment (thejameskyle) [inline lib/commands/updated.js]:
```
➜  lerna git:(master) ✗ git tags
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v1.0.5
v1.1.0
```
